In [1]:
import cv2

img = cv2.imread('watch.jpg',cv2.IMREAD_GRAYSCALE)

#img = cv2.imread('watch.jpg', 0)
# 1 corresponds to IMREAD_COLOR -1 to IMREAD_UNCHANGED 
#cv2.IMREAD_GRAYSCALE removes the alpha channel from the image which is the degree of opaqueness
# We convert to grayscale because it is much more simplified
#In case of OpenCV image is read as BGR and not as RGB
cv2.imshow('image',img)
cv2.waitKey(0) #waits for any key to be pressed to exit, necessary otherwise image will not wait on screen
cv2.destroyAllWindows()

In [ ]:
cv2.imwrite('watchgray.png',img)

In [ ]:
import cv2

cap = cv2.VideoCapture(0) #if you have multiple webcams in the system then the 0,1,2 specifies the webcam to use 
 
while(True):
    ret, frame = cap.read() #ret returns true or false
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) #cvtColor is used to convert the color 
 
    cv2.imshow('frame',gray)
    if cv2.waitKey(1) == ord('q'):
        break
cap.release() #release the camera to be able to use it again
cv2.destroyAllWindows()

waitKey(0) will pause your screen because it will wait infinitely for keyPress on your keyboard and will not refresh the frame(cap.read()) using your WebCam. waitKey(1) will wait for keyPress for just 1 millisecond and it will continue to refresh and read frame from your webcam using cap.read(). waitKey() returns the value of the key pressed. ord() sends a unicode value like the ascii value for that character

In [ ]:
import cv2

cap = cv2.VideoCapture(1)
fourcc = cv2.VideoWriter_fourcc(*'XVID')  #The codec
out = cv2.VideoWriter('output.avi',fourcc, 20.0, (640,480))

while(True):
    ret, frame = cap.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    out.write(frame)
    cv2.imshow('frame',gray)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
out.release()
cv2.destroyAllWindows()

In [ ]:
import cv2

img = cv2.imread('watch.jpg',cv2.IMREAD_COLOR)
cv2.line(img,(0,0),(150,150),(255,255,255),15)
#cv2.line(source image,start point,end point,color in bgr,thickness) 255 means maximum brightness of color

cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
import cv2

img = cv2.imread('watch.jpg',cv2.IMREAD_COLOR)
cv2.rectangle(img,(15,25),(200,150),(0,0,255),15) #if you do -1 instead of 15 then it means fill 
#cv2.rectangle(source image,left bottom corner of rectangle,right top corner,color in bgr,thickness) 255 means maximum brightness of color
cv2.circle(img,(100,63), 55, (0,255,0), -1)

cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np
img = cv2.imread('watch.jpg',cv2.IMREAD_COLOR)
pts = np.array([[10,5],[20,30],[70,20],[50,10]], np.int32)
cv2.polylines(img, [pts], True, (0,255,255), 3) #True means if you want to connect the final and initial points or not
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. A list is the Python equivalent of an array, but is resizeable and can contain elements of different types.

In [1]:
import cv2
img = cv2.imread('watch.jpg',cv2.IMREAD_COLOR)
font = cv2.FONT_HERSHEY_SIMPLEX
cv2.putText(img,'OpenCV',(0,130), font, 1, (200,255,155), 2, cv2.LINE_AA)
#cv2.putText(img,text,Starting point, font, size, color, spacing between digits, line type) Line_AA is for antialiasing i.e remove the stair like end pixels and make it smooth end pixels are made successively smooth and not abruptly

cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
import cv2
img = cv2.imread('watch.jpg',cv2.IMREAD_COLOR)
px = img[55,55]
print(px)

[29 31 42]


In [3]:
img[55,55] = [255,255,255]
px = img[55,55]
print(px)

[255 255 255]


In [4]:
roi = img[100:150,100:150]
print(roi)

[[[ 53  48  57]
  [ 53  48  57]
  [ 54  46  56]
  ...
  [ 36  36  42]
  [ 36  36  42]
  [ 56  56  62]]

 [[ 48  43  52]
  [ 50  45  54]
  [ 53  45  55]
  ...
  [ 36  34  40]
  [ 42  40  46]
  [ 39  37  43]]

 [[ 46  41  50]
  [ 47  42  51]
  [ 51  43  53]
  ...
  [ 33  33  39]
  [ 33  33  39]
  [ 56  56  62]]

 ...

 [[ 25  34  47]
  [ 27  36  49]
  [ 30  39  53]
  ...
  [105 114 128]
  [106 114 131]
  [106 114 131]]

 [[ 27  36  50]
  [ 26  35  49]
  [ 26  35  49]
  ...
  [ 96 110 129]
  [105 116 138]
  [109 120 142]]

 [[ 27  36  50]
  [ 25  34  48]
  [ 25  34  48]
  ...
  [101 114 136]
  [100 112 136]
  [107 117 141]]]


In [5]:
img[100:150,100:150] = [255,255,255]
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
import cv2
img = cv2.imread('watch.jpg',cv2.IMREAD_COLOR)
watch_face = img[37:111,107:194]
img[0:74,0:87] = watch_face

cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
import cv2
import numpy as np

# 500 x 250
img1 = cv2.imread('3D-Matplotlib.png')
img2 = cv2.imread('mainsvmimage.png')

add = img1+img2
#This add adds the pixel value and if a pixel value is greater than 255 then 256 is subtracted from the sum
#[55,166,177] + [56,66,197] = [111 232 118] and [240,200,165] + [40,125,200] = [24,69,109]
cv2.imshow('img1',img2)
cv2.imshow('img2',img1)
cv2.imshow('add',add)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
add = cv2.add(img1,img2) # adds the pixel values and if it isgreater than 255 then changed to 255
#E.g [125,125,125] + [12,10,100] = [137,135,225] and [240,200,165] + [40,125,200] = [255,255,255]
cv2.imshow('add',add)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
weighted = cv2.addWeighted(img1, 0.6, img2, 0.4, 0)
cv2.imshow('weighted',weighted)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
import cv2
import numpy as np

# Load two images
img1 = cv2.imread('3D-Matplotlib.png')
img2 = cv2.imread('mainlogo.png')

# I want to put logo on top-left corner, So I create a ROI
rows,cols,channels = img2.shape
roi = img1[0:rows, 0:cols]

# Now create a mask of logo and create its inverse mask
img2gray = cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)

# add a threshold
ret, mask = cv2.threshold(img2gray, 220, 255, cv2.THRESH_BINARY_INV) #the style depends on your usage

#cv2.threshold(img, lower limit, max value, thresholding style) any value above lower limit is changed to the max value 
#and below that to 0. There are many types but we mostly use the binary threshold, others are truncation and TOZERO which 
#are not useful. INVERSE LITERALLY INVERTS THE COLORS
# OTSZU THRESHOLDING STYLE IS QUITE INTERESTING, RARELY USED BUT SOLELY HAS THE POWER TO SOLVE CERTAIN TYPES OF PROBLEMS WHEN
#THE IMAGE IS NOISY. YOU CAN READ IF YOU WANT.
cv2.imshow('mask', mask)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
import cv2
import numpy as np

# Load two images
img1 = cv2.imread('3D-Matplotlib.png')
img2 = cv2.imread('mainlogo.png')

# I want to put logo on top-left corner, So I create a ROI
rows,cols,channels = img2.shape
roi = img1[0:rows, 0:cols ]

# Now create a mask of logo and create its inverse mask
img2gray = cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)

# add a threshold
ret, mask = cv2.threshold(img2gray, 220, 255, cv2.THRESH_BINARY_INV) #As the colors in the image are not very bright therefore 
# a threshold of 220 will capture all of them

mask_inv = cv2.bitwise_not(mask)
cv2.imshow("mask", mask)
cv2.imshow("mask_inv", mask_inv)
# Now black-out the area of logo in ROI
img1_bg = cv2.bitwise_and(roi,roi,mask = mask_inv)
#Mask is binary, the binary operation is operated only when mask is 1 i.e white
cv2.imshow("img1_bg", img1_bg)
# Take only region of logo from logo image.
img2_fg = cv2.bitwise_and(img2,img2,mask = mask)
cv2.imshow("img2_fg", img2_fg)
dst = cv2.add(img1_bg,img2_fg)
img1[0:rows, 0:cols ] = dst

cv2.imshow('res',img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
import cv2

img = cv2.imread('bookpage.jpg')
retval, threshold = cv2.threshold(img, 12, 255, cv2.THRESH_BINARY) 
#as we have applied threshold on colored image therefore each color channel ie BGR are converted to 255 or 0
cv2.imshow('original',img)
cv2.imshow('threshold',threshold)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:

grayscaled = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
retval, threshold = cv2.threshold(grayscaled, 10, 255, cv2.THRESH_BINARY)
cv2.imshow('threshold',threshold)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
th = cv2.adaptiveThreshold(grayscaled, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 115, 2)
#cv2.adaptiveThreshold(src, maxValue, adaptiveMethod, thresholdType, blockSize, C) c is the const which is subtracted
cv2.imshow('Adaptive threshold',th)
cv2.waitKey(0)
cv2.destroyAllWindows()

We haven't specified threshold beacuse the method specifies a local threshold on its own.
For the method ADAPTIVE_THRESH_MEAN_C , the threshold value T(x,y) is a mean of the blocksize X blocksize neighborhood of (x, y) minus C .
For the method ADAPTIVE_THRESH_GAUSSIAN_C , the threshold value T(x, y) is a weighted sum (cross-correlation with a Gaussian window) of the blocksize X blocksize neighborhood of (x, y) minus C . The default sigma (standard deviation) is used for the specified blockSize.

In [18]:
import cv2
import numpy as np

cap = cv2.VideoCapture(0)

while(1):
    _, frame = cap.read()
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    
    lower_red = np.array([150,150,50])
    upper_red = np.array([200,255,180])
    
    mask = cv2.inRange(hsv, lower_red, upper_red)
    res = cv2.bitwise_and(frame,frame, mask= mask)

    cv2.imshow('frame',frame)
    cv2.imshow('mask',mask)
    cv2.imshow('res',res)
    
    k = cv2.waitKey(5) & 0xFF
    if k == 27:
        break

cv2.destroyAllWindows()
cap.release()

We change to hsv so as to specify a range
![alt text](123.png "Title")
Hue -> Color 

Saturation -> Intensity

Value -> Darkness
![alt text](145.png "Title")

In [19]:
import cv2
import numpy as np

cap = cv2.VideoCapture(0)

while(1):

    _, frame = cap.read()
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    
    lower_red = np.array([150,150,50])
    upper_red = np.array([200,255,180])
    
    mask = cv2.inRange(hsv, lower_red, upper_red)
    res = cv2.bitwise_and(frame,frame, mask= mask)
    kernel = np.ones((15,15),np.float32)/225
    smoothed = cv2.filter2D(res,-1,kernel)
    #cv2.filter2D(src, ddepth, kernel) ddepth is the depth of the output image, -1 means to keep the depth of output same as the src image
    #The operation works like this: keep this kernel above a pixel, add all the 225 pixels below this kernel, take the 
    #average, and replace the central pixel with the new average value. This is essentially a low pass filter for an image
    cv2.imshow('Original',frame)
    cv2.imshow('res',res)
    cv2.imshow('Averaging',smoothed)

    k = cv2.waitKey(5) & 0xFF
    if k == 27:
        break

cv2.destroyAllWindows()
cap.release()

In [20]:
import cv2
import numpy as np

cap = cv2.VideoCapture(0)

while(1):

    _, frame = cap.read()
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    
    lower_red = np.array([150,150,50])
    upper_red = np.array([200,255,180])
    
    mask = cv2.inRange(hsv, lower_red, upper_red)
    res = cv2.bitwise_and(frame,frame, mask= mask)
    smoothed= cv2.blur(res,(3,3))
    cv2.imshow('Original',frame)
    cv2.imshow('res',res)
    cv2.imshow('Averaging',smoothed)

    k = cv2.waitKey(5) & 0xFF
    if k == 27:
        break

cv2.destroyAllWindows()
cap.release()

In [21]:
import cv2
import numpy as np

cap = cv2.VideoCapture(0)

while(1):

    _, frame = cap.read()
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    
    lower_red = np.array([150,150,50])
    upper_red = np.array([200,255,180])
    
    mask = cv2.inRange(hsv, lower_red, upper_red)
    res = cv2.bitwise_and(frame,frame, mask= mask)
    blur = cv2.GaussianBlur(res,(15,15),0) #here (15,15) is the kernel size and 0 is the sigma/std deviation
    cv2.imshow('Gaussian Blurring',blur)
    cv2.imshow('Original',frame)
    cv2.imshow('res',res)
    

    k = cv2.waitKey(5) & 0xFF
    if k == 27:
        break

cv2.destroyAllWindows()
cap.release()

In [22]:
import cv2
import numpy as np

cap = cv2.VideoCapture(0)

while(1):

    _, frame = cap.read()
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    
    lower_red = np.array([150,150,50])
    upper_red = np.array([200,255,180])
    
    mask = cv2.inRange(hsv, lower_red, upper_red)
    res = cv2.bitwise_and(frame,frame, mask= mask)
    median = cv2.medianBlur(res,15) #15 is the kernel size
    cv2.imshow('Median Blur',median)
    cv2.imshow('Original',frame)
    cv2.imshow('res',res)
    

    k = cv2.waitKey(5) & 0xFF
    if k == 27:
        break

cv2.destroyAllWindows()
cap.release()

In [23]:
import cv2
import numpy as np

cap = cv2.VideoCapture(0)

while(1):

    _, frame = cap.read()
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    
    lower_red = np.array([150,150,50])
    upper_red = np.array([200,255,180])
    
    mask = cv2.inRange(hsv, lower_red, upper_red)
    res = cv2.bitwise_and(frame,frame, mask= mask)
    bilateral = cv2.bilateralFilter(res,15,75,75)
    cv2.imshow('bilateral Blur',bilateral)
    cv2.imshow('Original',frame)
    cv2.imshow('res',res)
    

    k = cv2.waitKey(5) & 0xFF
    if k == 27:
        break

cv2.destroyAllWindows()
cap.release()

cv2.bilateralFilter(src, d, sigmaColor, sigmaSpace)

d is the diameter of each pixel neighbourhood which is used in filtering

sigmaColor – Filter sigma in the color space. A larger value of the parameter means that farther colors within 
the pixel neighborhood (see sigmaSpace ) will be mixed together, resulting in larger areas of semi-equal color.

sigmaSpace – Filter sigma in the coordinate space. A larger value of the parameter means that farther pixels will 
influence each other as long as their colors are close enough (see sigmaColor ). When d>0 , it specifies the 
neighborhood size regardless of sigmaSpace . Otherwise, d is proportional to sigmaSpace .

# Morphological Transforms

In [12]:
import cv2
import numpy as np

cap = cv2.VideoCapture(0)

while(1):

    _, frame = cap.read()
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    
    lower_red = np.array([150,150,50])
    upper_red = np.array([200,255,180])
    
    mask = cv2.inRange(hsv, lower_red, upper_red)
    res = cv2.bitwise_and(frame,frame, mask= mask)

    kernel = np.ones((5,5),np.uint8)
    erosion = cv2.erode(mask,kernel,iterations = 1)
    dilation = cv2.dilate(mask,kernel,iterations = 1)

    cv2.imshow('Original',frame)
    cv2.imshow('Mask',mask)
    cv2.imshow('Erosion',erosion)
    cv2.imshow('Dilation',dilation)

    k = cv2.waitKey(5) & 0xFF
    if k == 27:
        break

cv2.destroyAllWindows()
cap.release()

Erosion is where we will "erode" the edges. The way these work is we work with a slider (kernel). We give the slider a size, let's say 5 x 5 pixels. What happens is we slide this slider around, and if all of the pixels are white, then we get white, otherwise black. This may help eliminate some white noise. The other version of this is Dilation, which basically does the opposite: Slides around, if the entire area isn't black, then it is converted to white.

In [15]:
import cv2
import numpy as np
cap = cv2.VideoCapture(0)

while(1):

    _, frame = cap.read()
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    
    lower_red = np.array([150,150,50])
    upper_red = np.array([200,255,180])
    
    mask = cv2.inRange(hsv, lower_red, upper_red)
    res = cv2.bitwise_and(frame,frame, mask= mask)

    kernel = np.ones((5,5),np.uint8)
    
    opening = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)
    closing = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)

    cv2.imshow('Original',frame)
    cv2.imshow('Mask',mask)
    cv2.imshow('Opening',opening)
    cv2.imshow('Closing',closing)

    k = cv2.waitKey(5) & 0xFF
    if k == 27:
        break

cv2.destroyAllWindows()
cap.release()

The goal with opening is to remove "false positives" so to speak. Sometimes, in the background, you get some pixels here and there of "noise." The idea of "closing" is to remove false negatives. Basically this is where you have your detected shape, like our object, and yet you still have some black pixels within the object. Closing will attempt to clear that up.

MORPH_OPEN -> dilate(erode(src frame))

MORPH_CLOSE -> erode(dilate(src frame))

MORPH_GRAD -> dilate(src frame) - erode(src frame)

# Edge Detection

In [17]:
import cv2
import numpy as np

cap = cv2.VideoCapture(0)

while(1):

    _, frame = cap.read()
    cv2.imshow('Original',frame)
    edges = cv2.Canny(frame,100,200)
    cv2.imshow('Edges',edges)

    k = cv2.waitKey(5) & 0xFF
    if k == 27:
        break

cv2.destroyAllWindows()
cap.release()

cv2.Canny(src frame, threshold 1, threshold 2)

The smallest value between threshold1 and threshold2 is used for edge linking. The largest value is used to find initial 
segments of strong edges. This function is based on The canny edge detection algortihm

# Geometric Transformations

In [31]:
import cv2
import numpy as np

img = cv2.imread('watch.jpg')

res = cv2.resize(img,None,fx=2, fy=2, interpolation = cv2.INTER_CUBIC) #bicubic interpolation over 4x4 pixel neighborhood
#fx and fy are scale factors along x and y axis you can also do res = cv2.resize(img,(2*width, 2*height), interpolation = cv2.INTER_CUBIC)
cv2.imshow('asd', img)
cv2.imshow('img',res)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Translation
Translation is the shifting of object’s location. If you know the shift in (x,y) direction, let it be (t_x,t_y), you can create the transformation matrix M as follows:

M = \begin{bmatrix} 1 & 0 & t_x \\ 0 & 1 & t_y  \end{bmatrix}

In [35]:
import cv2
import numpy as np

img = cv2.imread('watch.jpg',0)
rows,cols = img.shape

M = np.float32([[1,0,100],[0,1,50]])
dst = cv2.warpAffine(img,M,(cols,rows)) #cols, rows is the size of output image
#warp affine basically applies the matrix M onto the image
cv2.imshow('asd', img)
cv2.imshow('img',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Rotation

In [39]:
img = cv2.imread('watch.jpg',0)
rows,cols = img.shape

M = cv2.getRotationMatrix2D((cols/2,rows/2),90,1)
#cv2.getRotationMatrix2D(center,angle,scale)
dst = cv2.warpAffine(img,M,(cols, rows))
cv2.imshow('asd', img)
cv2.imshow('img',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [57]:
img = cv2.imread('watch.jpg')
rows,cols,ch = img.shape

pts1 = np.float32([[50,50],[200,50],[50,200]])
pts2 = np.float32([[10,100],[200,50],[100,250]])

M = cv2.getAffineTransform(pts1,pts2)

dst = cv2.warpAffine(img,M,(cols,rows))
cv2.imshow('asd', img)

cv2.imshow('img',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [24]:
import cv2
import numpy as np
img = cv2.imread('sudoku.png')
rows,cols,ch = img.shape

pts1 = np.float32([[72,85],[480,72],[40,520],[510,520]])
pts2 = np.float32([[0,0],[500,0],[0,500],[500,500]])

M = cv2.getPerspectiveTransform(pts1,pts2)

dst = cv2.warpPerspective(img,M,(500,500))
cv2.imshow('asd', img)

cv2.imshow('img',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

![alt text](perspective.jpg "Title")

## Structure Analysis

In [29]:
image = cv2.imread("contour.jpg")
# Find edges
edges = cv2.Canny(image, 10, 100)
# Find Contours
contours, hierarchy = cv2.findContours(edges,cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
#Many diff types of modes and methods which you can explore later, retr_external outputs only the external contours 
#with a single level of hierarchy whereas there's retr_ccomp which outputs all contours with a two level hierarchy
print("Number of Contours is: " + str(len(contours)))
print(hierarchy)
cv2.drawContours(image, contours, -1, (0, 230, 255), 3)
#cv2.drawContours(image, contours, index of contour -1 means all, color, thickness)
cv2.imshow('Contours', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

Number of Contours is: 1
[[[-1 -1 -1 -1]]]


cv2.findContours(image, mode, method) Each contour is stored as a vector of points.
The input image can only be an 8 bit single channel image therefore you can use compare() , inRange() , threshold() , adaptiveThreshold() , Canny() etc for conversion 

##### hierarchy – 
Optional output vector, containing information about the image topology. It has as many elements as the number of contours. For each i-th contour contours[i] , the elements hierarchy[i][0] , hiearchy[i][1] , hiearchy[i][2] , and hiearchy[i][3] are set to 0-based indices in contours of the next and previous contours at the same hierarchical level, the first child contour and the parent contour, respectively. If for the contour i there are no next, previous, parent, or nested contours, the corresponding elements of hierarchy[i] will be negative.


In [49]:
image = cv2.imread("fitline.jpg")
# Find edges
edges = cv2.Canny(image, 10, 100)
x,y,w,h = cv2.boundingRect(edges)
#similar to contours this also requires a single channel image (essentialy a set of pts) therefore we apply canny. It gives
#us one corner x,y and width & height of rectangle which is of min size and encompass all the points.
img = cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,0),2)
#cv2.rectangle(image, (x,y), (x+w,y+h), color, thickness)
cv2.imshow('Contours', img)
cv2.waitKey(0)
cv2.destroyAllWindows()


There is another feature called convexHull, it will give out a minimum bounding arbitary shape like if you want a min bound of your hand.
![alt text](conv.jpg "Title") 
The arrows in this picture depict the convexity defects

cv2.isContourConvex is used to find if the contour is convex or not

In [64]:
import cv2
image = cv2.imread("fitline.jpg")
# Find edges
edges = cv2.Canny(image, 150, 200)
contours, hierarchy = cv2.findContours(edges,cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
(x,y),radius = cv2.minEnclosingCircle(contours[1])
#similarly a min area rectangle, ellipse functions are also there. 
#for minimum bounding rect or min bounding circle a matrix/numpy array is required to you have to input a contour, edges etc
#can't be used
center = (int(x),int(y))
radius = int(radius)
img = cv2.circle(image,center,radius,(0,255,0),2)
cv2.imshow('Contours', img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [78]:
import cv2
import numpy as np
image = cv2.imread("fitline.jpg")
# Find edges
edges = cv2.Canny(image, 150, 200)
contours, hierarchy = cv2.findContours(edges,cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
rect = cv2.minAreaRect(contours[1])

box = cv2.boxPoints(rect)
box = np.int0(box)
im = cv2.drawContours(image,[box],0,(0,0,255),2)
cv2.imshow('Contours', im)

cv2.waitKey(0)
cv2.destroyAllWindows()


Output of minarearect is in the form (x-coordinate, y-coordinate),(width, height), rotation
boxPoints converts the output into vertices of rectangle and int0 converts them to integers and therefore we get a contour type input 

In [2]:
import cv2
import numpy as np


planets= cv2.imread('planet.jpg')
gray_img=cv2.cvtColor(planets,cv2.COLOR_BGR2GRAY)
img= cv2.medianBlur(gray_img,5)

circles= cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,120,param1=100,param2=30,minRadius=10,maxRadius=0)
circles= np.uint16(np.around(circles))
for i in circles[0,:]:

    cv2.circle(planets,(i[0],i[1]),i[2],(0,255,0),6)

    cv2.circle(planets,(i[0],i[1]),2,(0,0,255),3)

cv2.imshow("HoughCirlces",planets)
cv2.waitKey()
cv2.destroyAllWindows()

cv2.HoughCircles(image, method, dp, minDist, circles, param1, param2, minRadius, maxRadius) <br />
<b>dp</b> = accumulator_resolution/image_resolution <br />
<b>minDist</b>= min distance between two detected circles. If the parameter is too small, multiple neighbor circles may be falsely detected in addition to a true one. If it is too large, some circles may be missed. <br />
<b>Circles</b>- Output vector<br />
<b>param1</b> – First method-specific parameter. In case of CV_HOUGH_GRADIENT , it is the higher threshold of the two passed to the Canny() edge detector (the lower one is twice smaller). <br />
<b>param2</b> – Second method-specific parameter. In case of CV_HOUGH_GRADIENT , it is the accumulator threshold for the circle centers at the detection stage. The smaller it is, the more false circles may be detected. Circles, corresponding to the larger accumulator values, will be returned first. <br />
<b>minRadius </b>– Minimum circle radius. <br />
<b>maxRadius</b> – Maximum circle radius.


In [25]:
import cv2
import numpy as np

img = cv2.imread('sudoku.png')
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)


edges = cv2.Canny(gray,100,200,apertureSize = 3)
cv2.imshow('edges',edges)


minLineLength = 1
maxLineGap = 1000
lines = cv2.HoughLinesP(edges,1,np.pi/180,150,minLineLength=minLineLength,maxLineGap=maxLineGap)
for line in lines:
    for x1,y1,x2,y2 in line:
        cv2.line(img,(x1,y1),(x2,y2),(0,255,0),2)

cv2.imshow('hough',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

cv2.HoughLinesP(image, rho, theta, threshold, lines, minLineLength, maxLineGap)
P stands for probablistic and this is the optimised version of HoughLines and is faster,easier to use and more effecient
input should be an 8 bit single channel image<br />
<b>rho</b> – Distance resolution of the accumulator in pixels.Low values of rho give precision <br />
<b>theta</b> – Angle resolution of the accumulator in radians. better to keep pi/180 i.e 1 degree.<br />
<b>threshold</b> – Accumulator threshold parameter. Only those lines are returned that get enough votes .threshold. <br />
<b>minLineLength</b> – Minimum line length. Line segments shorter than that are rejected. <br />
<b>maxLineGap</b> – Maximum allowed gap between points on the same line to link them.



In [3]:
import numpy as np
import cv2

cap = cv2.VideoCapture('openbg1.mp4')
fgbg = cv2.createBackgroundSubtractorMOG2()

while(1):
    ret, frame = cap.read()

    fgmask = fgbg.apply(frame)
 
    cv2.imshow('fgmask',frame)
    cv2.imshow('frame',fgmask)

    
    k = cv2.waitKey(30) & 0xff
    if k == 27:
        break
    

cap.release()
cv2.destroyAllWindows()

## Cascade Classifier

Haar Cascade is a machine learning object detection algorithm used to identify objects in an image or video and based on the concept of ​​ features proposed by Paul Viola and Michael Jones
https://github.com/opencv/opencv/tree/master/data/haarcascades

In [18]:
import numpy as np
import cv2


face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('haarcascade_eye.xml')

cap = cv2.VideoCapture(0)
while 1:
    ret, img = cap.read()
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.1, 1)
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
        roi_gray = gray[y:y+h, x:x+w]
        roi_color = img[y:y+h, x:x+w]
        eyes = eye_cascade.detectMultiScale(roi_gray, 1.3)
        for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
    cv2.imshow('img',img)
    k = cv2.waitKey(30) & 0xff
    if k == 27:
        break

cap.release()
cv2.destroyAllWindows()

cv2.CascadeClassifier.detectMultiScale(image, scaleFactor, minNeighbors)
scale means that the image is scaled by this amount for optimised detection but if it is very high then there can be issues like if you bring your face close to the camera then it will not be able to detect your face because it is seeing the frame as 3X. Also these are optional parameters only image is necessary as you can see in the eye detection

minNeighbors – Parameter specifying how many neighbors each candidate rectangle should have to retain it.
Higher value means less number of detections but with higher quality i.e less number of false positives.

Very useful and can be used to create multiple projects like blink rate detection, face mask detection etc.

#### There are many other features like template matching, grabcut, corner detection etc which I didn't include due to time constraint and their level of complexity. If you want to explore more about them then you can refer to the extra links we will share

#                           <center><----- THANK YOU-----> </center>                      
    
Credits- Bhuvan Aggarwal (190040026)<br />
For any doubts or future resources feel free to contact me.